#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image:
- Visual Studio 2022
- Ubuntu2004

#---------------------------------#
#       build configuration       #
#---------------------------------#

# scripts to run before build
before_build:
  - cd src
  - dotnet restore

build_script:
  - # Install Linux build-dependencies
  - sh: sudo apt-get update -y && sudo apt-get -y install cmake build-essential libssl-dev pkg-config libboost-all-dev libsodium-dev libzmq5
  - # Publish
  - cd Miningcore
  - dotnet publish -c Release --framework net6.0
  - # Publish Artifacts
  - sh: (cd bin/Release/net6.0 && mkdir miningcore && cp -r publish/* miningcore && tar cf miningcore-linux-ubuntu-x64.tar.gz miningcore && appveyor PushArtifact miningcore-linux-ubuntu-x64.tar.gz)
  - cmd: cd bin\Release\net6.0 && mkdir miningcore && xcopy publish\* miningcore /S && 7z a miningcore-win-x64.zip miningcore && appveyor PushArtifact miningcore-win-x64.zip && cd ..\..\..
  - # Build Tests
  - cd ../Miningcore.Tests
  - dotnet build -c Release --framework net6.0

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to run tests again only selected assemblies and/or categories
test_script:
 - dotnet test -c Release --no-build

before_test:
  - sh: cp -v $APPVEYOR_BUILD_FOLDER/src/Miningcore/bin/Release/net6.0/publish/*.so $APPVEYOR_BUILD_FOLDER/src/Miningcore.Tests/bin/Release/net6.0/

#---------------------------------#
#         notifications           #
#---------------------------------#
