# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  batch: true
  branches:
    include:
    - develop
pr: none

pool:
  name: mue1-ncrypto-int-ado-vm-ubuntu

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: Use dotnet 6.x
  inputs:
    packageType: 'sdk'
    version: '6.x'
- task: AzureKeyVault@2
  displayName: Pull secrets
  inputs:
    azureSubscription: 'NonProd App SP'
    KeyVaultName: 'mue1-ncrypto-dev-kv'
    SecretsFilter: '*'
    RunAsPreJob: false
- task: Bash@3
  displayName: Run build
  inputs:
    filePath: './scripts/build_test_pipeline.sh'
    arguments: '$(System.DefaultWorkingDirectory) $(Build.ArtifactStagingDirectory) $(buildConfiguration)'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
  env:
    PERSISTENCE_POSTGRES_HOST: $(persistence-postgres-host)
    PERSISTENCE_POSTGRES_USER: $(persistence-postgres-user)
    PERSISTENCE_POSTGRES_PASSWORD: $(persistence-postgres-password)
    PERSISTENCE_COSMOS_ENDPOINTURL: $(persistence-cosmos-endpointUrl)
    PERSISTENCE_COSMOS_AUTHORIZATIONKEY: $(persistence-cosmos-authorizationKey)
    PERSISTENCE_COSMOS_DATABASEID: $(persistence-cosmos-databaseId)
#- task: DotNetCoreCLI@2
#  displayName: Run tests
#  inputs:
#    command: 'test'
#    arguments: '--no-build --filter "FullyQualifiedName~PayoutTests" ./Miningcore.Integration.Tests.dll'
#    testRunTitle: 'NCrypto_Pool'
#    workingDirectory: '$(Build.ArtifactStagingDirectory)'
- upload: $(Build.ArtifactStagingDirectory)
  displayName: 'Publish package'
  artifact: drop